import '@/styles/styles.scss'
import 'react-loading-skeleton/dist/skeleton.css'
import { Archivo, Lora } from 'next/font/google'
import SessionProvider from '../components/layout/providers/SessionProvider'

const font = Archivo({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  style: ['normal'],
  variable: '--font-poppins' 
})

const headingFont = Lora({
  subsets: ['latin'],
  variable: '--font-tajawal',
  weight: ['400', '500', '700'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="assets/images/favicon.ico"
          type="image/png"
        />
      </head>
      <body className={`${font.variable} ${headingFont.variable}`}>
        {children}
      </body>
    </html>
  )
}
